name: iOS CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ["latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode ${{ matrix.xcode }}
        if: matrix.xcode != 'latest'
        run: sudo xcode-select -s "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"

      - name: Xcode version
        run: xcodebuild -version

      - name: Build, test, and capture screenshot (iOS Simulator)
        run: |
          set -e
          xcodebuild -project ArchiveManager.xcodeproj \
            -scheme ArchiveManager \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15 Pro' \
            -configuration Debug \
            -derivedDataPath DerivedData \
            build test
          DEVICE_NAME='iPhone 15 Pro'
          APP_PATH="$(pwd)/DerivedData/Build/Products/Debug-iphonesimulator/ArchiveManager.app"
          xcrun simctl boot "$DEVICE_NAME" || true
          xcrun simctl bootstatus "$DEVICE_NAME" -b
          xcrun simctl install "$DEVICE_NAME" "$APP_PATH"
          xcrun simctl launch "$DEVICE_NAME" com.example.ArchiveManager || true
          sleep 2
          mkdir -p ci_screenshots
          xcrun simctl io "$DEVICE_NAME" screenshot "ci_screenshots/iphone15pro.png"

      - name: Upload fullscreen device screenshot
        uses: actions/upload-artifact@v4
        with:
          name: ios-screenshots
          path: ci_screenshots
